spring:
  mongodb:
    uri: mongodb://root:BYzs4JjM7QPDlHpoUQ3qk7gBcdGtZcUwq_0qhpsgmc9ZXMni@23f87621-56fe-480d-bfc9-6f6ea46ef3de.asia-south1.firestore.goog:443/eca-6970?loadBalanced=true&tls=true&authMechanism=SCRAM-SHA-256&retryWrites=false